Elearning/config/routes.rb
Rails.application.routes.draw do

  get 'words/index'

  get 'sessions/new'

  root             'static_pages#home'
  get 'guide' => 'static_pages#guide'
  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :categories do
    member do
      post "check"
    end
  end
  resources :words

end

Elearning/app/models/activity.rb
class Activity < ActiveRecord::Base
end

Elearning/app/models/category.rb
class Category < ActiveRecord::Base
	has_many :words
end

Elearning/app/models/result.rb
class Result < ActiveRecord::Base
end

Elearning/app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 250 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
end

Elearning/app/models/word.rb
class Word < ActiveRecord::Base
	belongs_to :category
end

Elearning/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  include SessionsHelper
end

Elearning/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index 
		@categories = Category.all
	end

	def show
    @category = Category.find_by(params[:id])
    id = params[:id]
    #@words = @category.words.find_by_sql "select * from words where (words.id not in (select distinct word_id from results)) and (category_id = id) order by rand() limit 20"
    @words = Word.find_by_sql ["select * from words where (words.id not in (select word_id from results where user_id = ?)) and (category_id = ?) order by rand() limit 20",session[:user_id],id]
    #@words = Word.find_by_sql ["select * from words where (words.id not in (select distinct word_id from results where word_id in (select word_id from results where user_id = ?))) and (category_id = ?) order by rand() limit 20",session[:id],id]
   #  @words.each do |word|
  	# 	Result.create(:user_id => session[:user_id], :word_id => word.id, :category_id => params[:id])
  	# end

  	#if there are words to learn in category, update activities table
  	#else don't update
  	if @words.count > 0
  		Activity.create(:category_id => params[:id], :word_learned_quantity => @words.count, :user_id => session[:user_id])
  	end
  end

  def check
  	show
  	@count = 0;
  	#@posts = []
  	pos = 1
  	@words.each do |word|
  		id = pos.to_s
  		if word.vi == params[id]
  			@count = @count + 1
  		else
  			params[id] = -1
  		end
  		# id = pos.to_s
  		# @posts.push(params[id])
  		pos = pos + 1
  	end
  end
end

Elearning/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
    if user #&& user.authenticate(params[:session][:password])
  		log_in user
  		redirect_to user
  	else
  		flash[:danger] = 'Invalid email/password combination'
  		render 'new'
  	end
  end

  def destroy
  	log_out
  	redirect_to root_url
  end
end

Elearning/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def guide
  end
end

Elearning/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
    @user = User.find(params[:id])
    @activities = Activity.find_by_sql ["select * from activities where user_id = ?",session[:user_id]]
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      log_in @user #gan session de chuyen sang trang thai da login.neu khong co dong nay thi sau khi signup xong chi 
                    # chuyen sang trang show, chu login ko chuyen thanh account
  		flash[:success] = "Welcome to the E-Learning System"
  		redirect_to @user
  	else
  	  render 'new'
  	end
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :password, :email, :birthday, :address, :phone_number)
  	end

end

Elearning/app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
  	if params['category'] && params['learn']
  		if params['learn'] == 'all'
  			@words = Word.find_by_sql ["select * from words where category_id = ?",params['category']]
  		end
  		if params['learn'] == 'learned'
  			@words = Word.find_by_sql ["select * from words where (words.id in (select word_id from results where user_id = ?)) and (category_id = ?)",session[:user_id],params['category']]
  		end
  		if params['learn'] == 'notlearned'
  			@words = Word.find_by_sql ["select * from words where (words.id not in (select word_id from results where user_id = ?)) and (category_id = ?)",session[:user_id],params['category']]
  		end
  	end
  end

  def new
  	@word = Word.new
  end
end

Elearning/app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.       # Documentation comment
  def full_title(page_title = '')                     # Method def, optional arg
    base_title = "Ruby on Rails Tutorial Sample App"  # Variable assignment
    if page_title.empty?                              # Boolean test
      base_title                                      # Implicit return
    else
      page_title + " | " + base_title                 # String concatenation
    end
  end
end

Elearning/app/helpers/categories_helper.rb
module CategoriesHelper
end

Elearning/app/helpers/sessions_helper.rb
module SessionsHelper
	# Logs in the given user
	def log_in(user)
		session[:user_id] = user.id
	end

	# Returns the current logged-in user(if any)
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	# Returns true if the user is logged in, false otherwise
	def logged_in?
		!current_user.nil?
	end

	# Logs out the current user
	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
end

Elearning/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

Elearning/app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  # def gravatar_for(user)
  #   gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
  #   gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
  #   image_tag(gravatar_url, alt: user.name, class: "gravatar")
  # end
  
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

Elearning/app/helpers/words_helper.rb
module WordsHelper
	def filter
		
	end
end

Elearning/app/views/categories/check.html.erb
<h1>Result : <%= @count %>/20</h1>
<% temp = 1 %>
<% @words.each do |word| %>
  <li>
    <div>
      <%#= gravatar_for category, size: 50 %>
      <%#= link_to category.name, category %>        
      <p> 
      	<% if params[temp.to_s] == -1 %>
      		<span style="color: red; margin-right: 20px">X</span> 
      	<% else %>
      		<span style="color: red; margin-right: 20px">O</span> 
      	<% end %>
      	<span style="margin-right: 20px"><%= word.en %></span> : <span style="margin-left: 20px"><%= word.vi %></span>
      </p>
    </div>
  </li>
  <% temp = temp + 1 %>
<% end %>

Elearning/app/views/categories/index.html.erb
<% provide(:title, 'All categories') %>
<h1>All categories</h1>

<ul class="categories">
  <% @categories.each do |category| %>
    <li>
      <div>
      	<%#= gravatar_for category, size: 50 %>
	      <%#= link_to category.name, category %>
	      <h2><%= category.title %>  <span style="color: red">You've learned <%= Result.where("category_id = ? and user_id = ?",category.id,session[:user_id]).count %>/<%= Word.where("category_id = ?",category.id).count %></span></h2>
	      <p><%= category.description %></p>
	      <button type="button" class="btn btn-success btn-lg"><%= link_to "Start", category %></button>
      </div>
    </li>
  <% end %>
</ul>

Elearning/app/views/categories/show.html.erb
<script type="text/javascript">
  $(document).ready(function(){
    $(".ans").click(function(){
      //Them :checked de khi chon bat ki mot dap an trong mot cau chi tinh la 1 lan click => tien trinh lesson
      var a = $(".ans:checked").length;
      $("#process").text(a);
    });
  });
</script>

<ul class="categories" style="list-style-type: none">
  <% temp = 1 %>
  <h2><%= Category.find(params[:id]).title %> <span style="color: green"><span id="process">0</span>/20</span></h2>
  <form action="/categories/<%= params[:id] %>/check" method="post">
    <% @words.each do |word| %>
      <li>
        <div>
          <%#= gravatar_for category, size: 50 %>
          <%#= link_to category.name, category %>        
          <p><%= temp %>. <%= word.en %> ?</p>
          <input type="radio" name="<%= temp %>" value="<%= word.ans_a %>" class="ans"> <%= word.ans_a %><br>
          <input type="radio" name="<%= temp %>" value="<%= word.ans_b %>" class="ans"> <%= word.ans_b %><br>
          <input type="radio" name="<%= temp %>" value="<%= word.ans_c %>" class="ans"> <%= word.ans_c %><br>
          <input type="radio" name="<%= temp %>" value="<%= word.ans_d %>" class="ans"> <%= word.ans_d %><br>
          <% temp = temp + 1 %>
        </div>
      </li>
    <% end %>
    <input type="submit" value="Check">
  </form>
</ul>
<button type="button" class="btn btn-success btn-lg"><%= link_to "Back", categories_path %></button>

Elearning/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

Elearning/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Guide",   guide_path %></li>
        <% if logged_in? %>
          <li><%#= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

Elearning/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

Elearning/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js' %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

Elearning/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

Elearning/app/views/static_pages/guide.html.erb
<h1>Guide</h1>

Elearning/app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%#= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

Elearning/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    	<%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :birthday %>
      <%= f.text_field :birthday, class: 'form-control' %>

      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>

      <%= f.label :phone_number %>
      <%= f.text_field :phone_number, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

Elearning/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
  	<p>
  	  <button type="button" class="btn btn-success btn-lg"><%= link_to "Word", words_path %></button>
  	  <button type="button" class="btn btn-success btn-lg"><%= link_to "Lession", categories_path %></button>
  	</p>
    <h2>Activities</h2><hr>
    <ul class="activities">
      <% @activities.each do |activity| %>
        <li>
          <div>
            <% a = Category.find_by_sql ["select * from categories where id = ?",activity.category_id] %>
            <%#= gravatar_for activity.id, size: 50 %>
            <%#= link_to activity.name, activity %>           
            <p>Learned <%= activity.word_learned_quantity %> words in Lesson "<%=  %>".( <%= activity.created_at %> )</p>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

Elearning/app/views/words/index.html.erb
<% provide(:title, 'All words') %>
<h1>All words</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%#= form_tag('/words', :method => :get) do %>
    <%#= text_field_tag "username" %>
    <%#= submit_tag "Submit", :html => {:id => "abc"} %>
    <%# end %>
    <form action="/words" method="get">
    	<select name="category">
    		<% Category.all.each do |category| %>
    			<option value="<%= category.id %>"><%= category.title %></option>
    		<% end %>
    	</select>
    	<input type="radio" name="learn" value="learned"> Learned
    	<input type="radio" name="learn" value="notlearned"> Not learned
    	<input type="radio" name="learn" value="all"> All
    	<input type="submit" value="Filter">
    </form>
  </div>
</div>

<% temp = 1 %>
<ul class="categories" style="list-style-type: none">
  <% if @words %>
  	<% @words.each do |word| %>
	    <li>
	      <div>
	      	<%#= gravatar_for category, size: 50 %>
		      <%#= link_to category.name, category %>
		      <p><%= temp %>. <%= word.en %> : <%= word.vi %></p>
	      </div>
	    </li>
	    <% temp = temp + 1 %>
	  <% end %>
  <% end %>
</ul>